// web/src/views/SetupView.svelte
<script lang="ts">
  /** 初始化向导（FR-OPS-02）：两件事——密钥与登录。步骤编号在此是真序列，故允许编号。
   *
   * 密钥写入 config.yaml（不入库），凭据类字段重启才生效；登录会话落 sessions/。
   * 本页是唯一不套侧栏/顶栏/播放条的全屏闸门，故自带页面容器（§2.2 页面外边距）。
   */
  import { api, errorText } from "$lib/api/client";
  import type { SetupSecretsPayload } from "$lib/api/types";
  import { t } from "$lib/i18n/index.svelte";
  import { navigate, pathOf } from "$lib/router.svelte";
  import { session } from "$lib/stores/session.svelte";
  import { Button } from "$lib/components/ui/button";
  import { Checkbox } from "$lib/components/ui/checkbox";
  import { Input } from "$lib/components/ui/input";
  import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
  } from "$lib/components/ui/select";
  import Field from "$lib/components/app/Field.svelte";
  import Lamp from "$lib/components/app/Lamp.svelte";
  import Note from "$lib/components/app/Note.svelte";

  let apiId = $state("");
  let apiHash = $state("");
  let botToken = $state("");
  let useProxy = $state(false);
  let proxyScheme = $state("socks5");
  let proxyHost = $state("");
  let proxyPort = $state("1080");

  let phone = $state("");
  let code = $state("");
  let password = $state("");
  let codeHash = $state("");

  let busy = $state(false);
  let notice = $state("");
  let error = $state("");

  const status = $derived(session.setup);
  const keysReady = $derived(Boolean(status?.has_api_id && status?.has_api_hash));
  const done = $derived(Boolean(status?.connected));

  async function saveSecrets() {
    busy = true;
    error = "";
    notice = "";
    try {
      const payload: SetupSecretsPayload = {};
      if (apiId.trim()) payload.api_id = Number(apiId.trim());
      if (apiHash.trim()) payload.api_hash = apiHash.trim();
      if (botToken.trim()) payload.bot_token = botToken.trim();
      if (useProxy) {
        payload.proxy = {
          scheme: proxyScheme,
          hostname: proxyHost.trim(),
          port: Number(proxyPort.trim()) || 1080,
        };
      }
      await api.post("/api/setup/secrets", payload);
      await session.loadSetup();
      notice = t("setup.savedRestart");
    } catch (err) {
      error = errorText(err, t("common.error"));
    } finally {
      busy = false;
    }
  }

  async function sendCode() {
    busy = true;
    error = "";
    notice = "";
    try {
      const resp = await api.post<{ code_hash: string }>("/api/auth/telegram/send-code", {
        phone: phone.trim(),
      });
      codeHash = resp.code_hash;
      notice = t("setup.codeSent");
    } catch (err) {
      error = errorText(err, t("common.error"));
    } finally {
      busy = false;
    }
  }

  async function signIn() {
    busy = true;
    error = "";
    try {
      await api.post("/api/auth/telegram/sign-in", {
        phone: phone.trim(),
        code: code.trim(),
        code_hash: codeHash,
        password: password.trim() || undefined,
      });
      await Promise.all([session.loadSetup(), session.loadMe()]);
      navigate(pathOf("dashboard"));
    } catch (err) {
      error = errorText(err, t("common.error"));
    } finally {
      busy = false;
    }
  }
</script>

<div class="mx-auto flex min-h-dvh w-full max-w-[560px] flex-col gap-4 p-4 md:gap-6 md:p-6">
  <header class="flex flex-col gap-1">
    <p class="tabular text-caption text-muted-foreground">{t("app.repo")}</p>
    <h1 class="text-h1 font-bold">{t("setup.title")}</h1>
    <p class="text-body text-muted-foreground">{t("setup.lede")}</p>
  </header>

  <section class="card overflow-hidden">
    <h2 class="p-4 text-h2 font-semibold md:p-5">{t("setup.checklist")}</h2>
    <ul>
      <li
        class="flex items-center justify-between gap-3 border-b border-rule px-5 py-3 last:border-b-0"
      >
        <span class="text-body">api_id</span>
        <Lamp
          tone={status?.has_api_id ? "done" : "fail"}
          label={status?.has_api_id ? t("setup.ready") : t("setup.missing")}
        />
      </li>
      <li
        class="flex items-center justify-between gap-3 border-b border-rule px-5 py-3 last:border-b-0"
      >
        <span class="text-body">api_hash</span>
        <Lamp
          tone={status?.has_api_hash ? "done" : "fail"}
          label={status?.has_api_hash ? t("setup.ready") : t("setup.missing")}
        />
      </li>
      <li
        class="flex items-center justify-between gap-3 border-b border-rule px-5 py-3 last:border-b-0"
      >
        <span class="text-body">bot_token</span>
        <Lamp
          tone={status?.has_bot_token ? "done" : "idle"}
          label={status?.has_bot_token ? t("setup.ready") : t("setup.optionalMissing")}
        />
      </li>
      <li
        class="flex items-center justify-between gap-3 border-b border-rule px-5 py-3 last:border-b-0"
      >
        <span class="text-body">{t("setup.proxy")}</span>
        <Lamp
          tone={status?.proxy ? "done" : "idle"}
          label={status?.proxy ? t("setup.proxyOn") : t("setup.proxyOff")}
        />
      </li>
      <li
        class="flex items-center justify-between gap-3 border-b border-rule px-5 py-3 last:border-b-0"
      >
        <span class="text-body">{t("setup.connection")}</span>
        <Lamp
          tone={status?.connected ? "done" : "fail"}
          label={status?.connected ? t("app.connected") : t("app.disconnected")}
        />
      </li>
    </ul>
  </section>

  {#if done}
    <section class="card flex flex-col gap-4 p-4 md:p-6">
      <h2 class="text-h2 font-semibold">{t("setup.doneTitle")}</h2>
      <p class="text-body text-muted-foreground">{t("setup.doneHint")}</p>
      <Button size="lg" class="self-start" onclick={() => navigate(pathOf("dashboard"))}>
        {t("setup.enter")}
      </Button>
    </section>
  {:else}
    <section class="card flex flex-col gap-4 p-5 md:p-6">
      <div class="flex flex-col gap-1">
        <h2 class="text-h2 font-semibold">{t("setup.step1")}</h2>
        <p class="text-body text-muted-foreground">{t("setup.step1Hint")}</p>
      </div>

      <Field label={t("setup.apiId")} for="setup-api-id">
        <Input id="setup-api-id" class="tabular" bind:value={apiId} />
      </Field>
      <Field label={t("setup.apiHash")} for="setup-api-hash">
        <Input id="setup-api-hash" class="tabular" bind:value={apiHash} />
      </Field>
      <Field label={`${t("setup.botToken")} (${t("setup.optional")})`} for="setup-bot-token">
        <Input id="setup-bot-token" class="tabular" type="password" bind:value={botToken} />
      </Field>

      <div class="flex flex-col gap-3">
        <label class="flex items-center gap-2 text-body">
          <Checkbox bind:checked={useProxy} />
          {t("setup.proxy")}
        </label>
        {#if useProxy}
          <p class="text-caption text-muted-foreground">{t("setup.proxyHint")}</p>
          <div class="grid grid-cols-3 gap-3">
            <Field label={t("setup.proxyScheme")}>
              <Select type="single" bind:value={proxyScheme}>
                <SelectTrigger class="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="socks5">socks5</SelectItem>
                  <SelectItem value="http">http</SelectItem>
                </SelectContent>
              </Select>
            </Field>
            <Field label={t("setup.proxyHost")} for="setup-proxy-host">
              <Input id="setup-proxy-host" class="tabular" bind:value={proxyHost} />
            </Field>
            <Field label={t("setup.proxyPort")} for="setup-proxy-port">
              <Input id="setup-proxy-port" class="tabular" bind:value={proxyPort} />
            </Field>
          </div>
        {/if}
      </div>

      <div class="flex flex-col gap-2">
        <Button size="lg" class="self-start" disabled={busy} onclick={() => void saveSecrets()}>
          {busy ? t("setup.saving") : t("setup.save")}
        </Button>
        {#if notice}<Note tone="done">{notice}</Note>{/if}
        {#if error}<Note tone="fail">{error}</Note>{/if}
      </div>
    </section>

    <section class="card flex flex-col gap-4 p-5 md:p-6">
      <div class="flex flex-col gap-1">
        <h2 class="text-h2 font-semibold">{t("setup.step2")}</h2>
        <p class="text-body text-muted-foreground">{t("setup.step2Hint")}</p>
      </div>

      {#if !keysReady}
        <Note tone="wait">{t("setup.step1Hint")}</Note>
      {:else}
        <Field label={t("setup.phone")} for="setup-phone">
          <div class="flex gap-2">
            <Input
              id="setup-phone"
              class="tabular flex-1"
              bind:value={phone}
              placeholder={t("setup.phonePlaceholder")}
            />
            <Button
              variant="outline"
              disabled={busy || phone.trim().length === 0}
              onclick={() => void sendCode()}
            >
              {busy ? t("setup.sending") : t("setup.sendCode")}
            </Button>
          </div>
        </Field>

        {#if codeHash}
          <Field label={t("setup.code")} for="setup-code">
            <Input id="setup-code" class="tabular" bind:value={code} />
          </Field>
          <Field label={`${t("setup.password2fa")} (${t("setup.optional")})`} for="setup-password">
            <Input id="setup-password" type="password" bind:value={password} />
          </Field>
          <Button
            size="lg"
            class="self-start"
            disabled={busy || code.trim().length === 0}
            onclick={() => void signIn()}
          >
            {busy ? t("setup.signingIn") : t("setup.signIn")}
          </Button>
        {/if}
      {/if}
    </section>
  {/if}
</div>

// web/src/views/SetupView.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useI18n } from "vue-i18n";
import { api, ApiError } from "@/api/client";

const { t } = useI18n();

interface SetupStatus {
  complete: boolean;
  has_api_id: boolean;
  has_api_hash: boolean;
  has_bot_token: boolean;
  proxy: boolean;
  connected: boolean;
}

const status = ref<SetupStatus | null>(null);

// 步骤 1：密钥
const apiId = ref("");
const apiHash = ref("");
const botToken = ref("");
// 代理
const useProxy = ref(false);
const proxyScheme = ref("socks5");
const proxyHost = ref("");
const proxyPort = ref("1080");
// 步骤 2：登录
const phone = ref("");
const code = ref("");
const password = ref("");
const codeHash = ref("");
const step = ref<"secrets" | "login" | "done">("secrets");
const busy = ref(false);
const message = ref("");
const error = ref("");

async function load() {
  status.value = await api.get<SetupStatus>("/api/setup/status");
  if (status.value.connected) step.value = "done";
  else if (status.value.has_api_id && status.value.has_api_hash) step.value = "login";
}

async function saveSecrets() {
  busy.value = true;
  error.value = "";
  try {
    await api.post("/api/setup/secrets", {
      api_id: apiId.value ? Number(apiId.value) : undefined,
      api_hash: apiHash.value || undefined,
      bot_token: botToken.value || undefined,
      proxy: useProxy.value
        ? {
            scheme: proxyScheme.value,
            hostname: proxyHost.value,
            port: Number(proxyPort.value) || 1080,
          }
        : undefined,
    });
    message.value = t("setup.savedRestart");
    await load();
    if (status.value?.has_api_id && status.value?.has_api_hash) step.value = "login";
  } catch (e) {
    error.value = e instanceof Error ? e.message : t("common.error");
  } finally {
    busy.value = false;
  }
}

async function sendCode() {
  busy.value = true;
  error.value = "";
  try {
    const resp = await api.post<{ code_hash: string }>("/api/auth/telegram/send-code", {
      phone: phone.value,
    });
    codeHash.value = resp.code_hash;
    message.value = t("setup.codeSent");
  } catch (e) {
    error.value = e instanceof ApiError ? e.message : t("common.error");
  } finally {
    busy.value = false;
  }
}

async function signIn() {
  busy.value = true;
  error.value = "";
  try {
    await api.post("/api/auth/telegram/sign-in", {
      phone: phone.value,
      code: code.value,
      code_hash: codeHash.value,
      password: password.value || undefined,
    });
    step.value = "done";
    await load();
  } catch (e) {
    error.value = e instanceof ApiError ? e.message : t("common.error");
  } finally {
    busy.value = false;
  }
}

onMounted(load);
</script>

<template>
  <div>
    <h1 class="mb-4 text-[17px] font-semibold text-hi">{{ t("setup.title") }}</h1>

    <div v-if="step === 'done'" class="rounded bg-raise px-4 py-3 text-[13px] text-signal">
      {{ t("setup.done") }}
    </div>

    <!-- 步骤 1：API 密钥 + 代理 -->
    <section v-if="step !== 'done'" class="mb-6 flex flex-col gap-4 rounded bg-raise p-4">
      <h2 class="text-[14px] font-medium text-hi">{{ t("setup.stepSecrets") }}</h2>
      <label class="flex flex-col gap-1.5">
        <span class="text-[13px] text-mid">api_id</span>
        <input v-model="apiId" type="text" class="rounded bg-inset px-3 py-2 font-mono text-[13px] text-hi" />
      </label>
      <label class="flex flex-col gap-1.5">
        <span class="text-[13px] text-mid">api_hash</span>
        <input v-model="apiHash" type="text" class="rounded bg-inset px-3 py-2 font-mono text-[13px] text-hi" />
      </label>
      <label class="flex flex-col gap-1.5">
        <span class="text-[13px] text-mid">bot_token ({{ t("setup.optional") }})</span>
        <input v-model="botToken" type="password" class="rounded bg-inset px-3 py-2 font-mono text-[13px] text-hi" />
      </label>

      <div class="flex flex-col gap-2">
        <label class="flex items-center gap-2 text-[13px] text-mid">
          <input v-model="useProxy" type="checkbox" />
          {{ t("setup.useProxy") }}
        </label>
        <div v-if="useProxy" class="grid gap-2 md:grid-cols-3">
          <select v-model="proxyScheme" class="rounded bg-inset px-3 py-2 text-[13px] text-hi">
            <option value="socks5">socks5</option>
            <option value="http">http</option>
          </select>
          <input v-model="proxyHost" type="text" :placeholder="t('setup.proxyHost')" class="rounded bg-inset px-3 py-2 text-[13px] text-hi" />
          <input v-model="proxyPort" type="text" :placeholder="t('setup.proxyPort')" class="rounded bg-inset px-3 py-2 text-[13px] text-hi" />
        </div>
      </div>

      <button
        class="self-start rounded bg-accent px-4 py-2 text-[13px] font-medium text-base"
        :disabled="busy"
        @click="saveSecrets"
      >
        {{ t("setup.saveSecrets") }}
      </button>
      <span v-if="message" class="text-[13px] text-signal">{{ message }}</span>
      <span v-if="error" class="text-[13px] text-fail">{{ error }}</span>
    </section>

    <!-- 步骤 2：Telegram 登录 -->
    <section v-if="step === 'login' || (step === 'secrets' && status?.has_api_id && status?.has_api_hash)"
      class="mb-6 flex flex-col gap-4 rounded bg-raise p-4">
      <h2 class="text-[14px] font-medium text-hi">{{ t("setup.stepLogin") }}</h2>
      <label class="flex flex-col gap-1.5">
        <span class="text-[13px] text-mid">{{ t("setup.phone") }}</span>
        <div class="flex gap-2">
          <input v-model="phone" type="text" placeholder="+86..." class="flex-1 rounded bg-inset px-3 py-2 text-[13px] text-hi" />
          <button class="rounded bg-accent px-3 py-2 text-[13px] font-medium text-base" :disabled="busy || !phone" @click="sendCode">
            {{ t("setup.sendCode") }}
          </button>
        </div>
      </label>
      <template v-if="codeHash">
        <label class="flex flex-col gap-1.5">
          <span class="text-[13px] text-mid">{{ t("setup.code") }}</span>
          <input v-model="code" type="text" class="rounded bg-inset px-3 py-2 text-[13px] text-hi" />
        </label>
        <label class="flex flex-col gap-1.5">
          <span class="text-[13px] text-mid">{{ t("setup.password2fa") }} ({{ t("setup.optional") }})</span>
          <input v-model="password" type="password" class="rounded bg-inset px-3 py-2 text-[13px] text-hi" />
        </label>
        <button
          class="self-start rounded bg-accent px-4 py-2 text-[13px] font-medium text-base"
          :disabled="busy || !code"
          @click="signIn"
        >
          {{ t("setup.signIn") }}
        </button>
      </template>
      <span v-if="error" class="text-[13px] text-fail">{{ error }}</span>
    </section>

    <p class="text-[12px] text-mid">{{ t("setup.hint") }}</p>
  </div>
</template>
