// web/src/views/TasksView.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useI18n } from "vue-i18n";
import { api } from "@/api/client";
import { useEventsStore } from "@/stores/events";

interface TaskRow {
  id: number;
  type: string;
  status: string;
  progress_bytes: number;
  total_bytes: number | null;
  retry_count: number;
  error: string | null;
}

const { t } = useI18n();
const tasks = ref<TaskRow[]>([]);
const events = useEventsStore();

async function load() {
  tasks.value = await api.get<TaskRow[]>("/api/downloads");
}

async function act(id: number, action: "cancel" | "pause" | "resume") {
  await api.post(`/api/downloads/${id}/${action}`);
  await load();
}

async function retryFailed() {
  await api.post("/api/downloads/retry-failed");
  await load();
}

onMounted(() => {
  load();
  // task.status 事件到达即刷新（SDD §1.4）
  const prevDispatch = events.dispatch.bind(events);
  events.dispatch = (type, payload) => {
    prevDispatch(type, payload);
    if (type === "task.status") load();
  };
});

function statusColor(status: string): string {
  if (status === "success" || status === "skipped") return "bg-signal";
  if (status === "failed") return "bg-fail";
  if (status === "paused") return "bg-warn";
  if (status === "downloading") return "bg-accent";
  return "bg-mid";
}
</script>

<template>
  <div>
    <div class="mb-4 flex items-center justify-between">
      <h1 class="text-[17px] font-semibold text-hi">{{ t("tasks.title") }}</h1>
      <button class="rounded px-3 py-1.5 text-[13px] text-accent hover:bg-raise" @click="retryFailed">
        {{ t("tasks.retryFailed") }}
      </button>
    </div>

    <p v-if="!tasks.length" class="text-[13px] text-mid">{{ t("tasks.empty") }}</p>

    <!-- 任务列表行：状态色点 + 文字（设计规范 §5：禁徽章底色块） -->
    <ul class="divide-y divide-hi/10">
      <li v-for="task in tasks" :key="task.id" class="py-2.5">
        <div class="flex h-10 items-center gap-3">
          <span
            class="inline-block h-2 w-2 shrink-0 rounded-full"
            :class="statusColor(task.status)"
            aria-hidden="true"
          />
          <div class="min-w-0 flex-1">
            <div class="truncate text-[13px] text-hi">
              #{{ task.id }} {{ t(`tasks.status.${task.status}`) }}
              <template v-if="task.error"> | {{ task.error }}</template>
            </div>
            <div
              v-if="task.status === 'downloading' && task.total_bytes"
              class="mt-1 h-0.5 w-full bg-hi/10"
            >
              <div
                class="progress-fill h-full bg-accent"
                :style="{ width: `${Math.min(100, (task.progress_bytes / task.total_bytes) * 100)}%` }"
              />
            </div>
          </div>
          <div class="flex gap-1.5">
            <button
              v-if="task.status === 'downloading'"
              class="rounded px-2 py-1 text-[12px] text-hi hover:bg-raise"
              @click="act(task.id, 'pause')"
            >
              {{ t("tasks.pause") }}
            </button>
            <button
              v-if="task.status === 'paused'"
              class="rounded px-2 py-1 text-[12px] text-hi hover:bg-raise"
              @click="act(task.id, 'resume')"
            >
              {{ t("tasks.resume") }}
            </button>
            <button
              v-if="['queued', 'downloading', 'paused'].includes(task.status)"
              class="rounded px-2 py-1 text-[12px] text-fail hover:bg-raise"
              @click="act(task.id, 'cancel')"
            >
              {{ t("tasks.cancel") }}
            </button>
          </div>
        </div>
      </li>
    </ul>
  </div>
</template>

// web/src/views/TasksView.svelte
<script lang="ts">
  /** 下载任务（设计规范 §10）：队列、进度、失败项。
   *
   * 列表事实源是 `queue`（DB 快照，SSE 状态事件触发重取）；进度/速率取 SSE 帧，
   * 所以行上的进度条是活的，而行的存在与否由数据库决定。
   */
  import { api, errorText } from "$lib/api/client";
  import type { Column } from "$lib/components/app/DataTable.svelte";
  import type { DownloadItemResult, TaskRow } from "$lib/api/types";
  import { formatEta, formatRate, formatSize, progressRatio } from "$lib/format";
  import { taskTypeText, t } from "$lib/i18n/index.svelte";
  import { queue } from "$lib/stores/queue.svelte";
  import { events } from "$lib/stores/events.svelte";
  import { statusText, taskTone } from "$lib/tone";
  import { Button } from "$lib/components/ui/button";
  import { Textarea } from "$lib/components/ui/textarea";
  import DataTable, { ROW_CLASS } from "$lib/components/app/DataTable.svelte";
  import EmptyState from "$lib/components/app/EmptyState.svelte";
  import Field from "$lib/components/app/Field.svelte";
  import Lamp from "$lib/components/app/Lamp.svelte";
  import Note from "$lib/components/app/Note.svelte";
  import PageHeader from "$lib/components/app/PageHeader.svelte";
  import ProgressBar from "$lib/components/app/ProgressBar.svelte";

  let links = $state("");
  let busy = $state(false);
  let notice = $state("");
  let failures = $state<DownloadItemResult[]>([]);
  let error = $state("");

  const failedCount = $derived(queue.failedCount);
  const columns = $derived<Column[]>([
    { key: "status", label: t("table.status"), class: "hidden w-20 shrink-0 sm:block" },
    { key: "task", label: t("table.task"), class: "min-w-0 flex-1" },
    { key: "progress", label: t("table.progress"), class: "hidden w-40 shrink-0 lg:block" },
    { key: "actions", label: "", class: "flex w-[136px] shrink-0 items-center justify-end gap-2" },
  ]);

  function liveProgress(task: TaskRow) {
    const frame = events.progress[task.id];
    return {
      received: frame?.progress_bytes ?? task.progress_bytes,
      total: frame?.total_bytes ?? task.total_bytes,
      speed: frame?.speed ?? null,
      eta: frame?.eta ?? null,
    };
  }

  async function act(id: number, action: "pause" | "resume" | "cancel") {
    error = "";
    try {
      await api.post(`/api/downloads/${id}/${action}`);
      await queue.refresh();
    } catch (err) {
      error = errorText(err, t("common.error"));
    }
  }

  async function enqueue() {
    const urls = links
      .split(/[\s,]+/)
      .map((value) => value.trim())
      .filter((value) => value.length > 0);
    if (urls.length === 0) return;
    busy = true;
    error = "";
    notice = "";
    failures = [];
    try {
      const resp = await api.post<{ items: DownloadItemResult[] }>("/api/downloads", { urls });
      const rejected = resp.items.filter((item) => item.error !== undefined);
      failures = rejected;
      notice = t("tasks.enqueueResult", { n: resp.items.length - rejected.length });
      if (rejected.length > 0) {
        notice = `${notice} · ${t("tasks.enqueueErrors", { n: rejected.length })}`;
      }
      links = "";
      await queue.refresh();
    } catch (err) {
      error = errorText(err, t("common.error"));
    } finally {
      busy = false;
    }
  }

  async function retryFailed() {
    error = "";
    notice = "";
    failures = [];
    try {
      const resp = await api.post<{ retried: number }>("/api/downloads/retry-failed");
      notice = t("tasks.retryResult", { n: resp.retried });
      await queue.refresh();
    } catch (err) {
      error = errorText(err, t("common.error"));
    }
  }
</script>

<PageHeader title={t("tasks.title")} lede={t("tasks.lede")}>
  {#snippet aside()}
    {#if failedCount > 0}
      <Button variant="outline" onclick={() => void retryFailed()}>
        {t("tasks.retryFailed")}
      </Button>
    {/if}
  {/snippet}
</PageHeader>

<div class="card p-4 md:p-5">
  <Field label={t("tasks.pasteLabel")} for="task-links">
    <div class="flex flex-col gap-3">
      <Textarea
        id="task-links"
        bind:value={links}
        rows={2}
        class="text-code"
        placeholder={t("tasks.pastePlaceholder")}
      />
      <div class="flex flex-wrap items-center gap-3">
        <Button size="lg" disabled={busy || links.trim().length === 0} onclick={() => void enqueue()}>
          {busy ? t("tasks.enqueuing") : t("tasks.enqueue")}
        </Button>
        {#if notice}
          <Note tone={failures.length > 0 ? "wait" : "done"}>{notice}</Note>
        {/if}
      </div>
    </div>
  </Field>
</div>

{#if error}
  <Note tone="fail">{error}</Note>
{/if}

{#each failures as item (item.url ?? `${item.chat_id}-${item.message_id}`)}
  <Note tone="fail">{item.url}：{item.error}</Note>
{/each}

{#if queue.tasks.length === 0}
  <EmptyState title={t("tasks.empty")} />
{:else}
  <DataTable {columns}>
    {#each queue.tasks as task (task.id)}
      {@const progress = liveProgress(task)}
      {@const tone = taskTone(task.status)}
      {@const finished = ["success", "failed", "skipped", "cancelled"].includes(task.status)}
      <li class="{ROW_CLASS} hover:bg-rule">
        <span class="hidden w-20 shrink-0 sm:block">
          <Lamp {tone} label={statusText(task.status)} />
        </span>

        <div class="flex min-w-0 flex-1 flex-col gap-0.5">
          <p class="truncate text-body font-medium">
            #{task.id} | {taskTypeText(task.type)}
          </p>
          {#if task.error}
            <p class="truncate text-caption text-destructive-text" title={task.error}>{task.error}</p>
          {:else if !finished}
            <p class="tabular truncate text-caption text-muted-foreground">
              {t("tasks.received", { size: formatSize(progress.received) })} ·
              {t("tasks.total", { size: formatSize(progress.total) })}
              {#if progress.speed}· {t("tasks.speed")} {formatRate(progress.speed)}{/if}
              {#if progress.eta}· {t("tasks.eta")} {formatEta(progress.eta)}{/if}
            </p>
          {:else if task.retry_count > 0}
            <p class="text-caption text-muted-foreground">
              {t("tasks.retryCount", { n: task.retry_count })}
            </p>
          {/if}
        </div>

        <div class="hidden w-40 shrink-0 lg:block">
          {#if !finished}
            <ProgressBar
              ratio={progressRatio(progress.received, progress.total)}
              label={`#${task.id}`}
            />
          {/if}
        </div>

        <div class="flex w-[136px] shrink-0 items-center justify-end gap-2">
          {#if task.status === "downloading"}
            <Button variant="outline" size="xs" onclick={() => void act(task.id, "pause")}>
              {t("tasks.pause")}
            </Button>
          {:else if task.status === "paused"}
            <Button variant="outline" size="xs" onclick={() => void act(task.id, "resume")}>
              {t("tasks.resume")}
            </Button>
          {/if}
          {#if ["queued", "downloading", "paused"].includes(task.status)}
            <Button variant="destructive" size="xs" onclick={() => void act(task.id, "cancel")}>
              {t("tasks.cancel")}
            </Button>
          {/if}
        </div>
      </li>
    {/each}
  </DataTable>
{/if}
